### ISSUE TITLE
Fix error when running pre-built binary

### ISSUE THREAD

**Issue by miklasr** [ESE-Peasy/PosturePerfection#105]
# Goal

Fix error running pre-built binary

Running from source works, but using the released binary causes the error below.

# Additional information

At run time:
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.1-dev) /home/pi/opencv_src/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

**Comment by Ashwin-MJ** [comment]
https://github.com/ESE-Peasy/PosturePerfection/blob/5f9b70889c98aeffaeddd9c236343a9582dd366d/PosturePerfection_install.sh#L13-L15

My bad - This link is incorrect. It should be: 

```
https://github.com/ESE-Peasy/PosturePerfection/raw/main/images/logo.png 
```
