### ISSUE TITLE
Get RPi up and running

### ISSUE THREAD

**Issue by miklasr** [ESE-Peasy/PosturePerfection#14]
Ensure everyone has a their RPi running with a simple test of the camera completed.

Follow documentation for setting up as per #18 

Tick once complete:
- [x] Andrew
- [x] Ashwin
- [x] Conor
- [x] Miklas

*Close this once the last person has theirs running.*

**Comment by C-Begley** [comment]
Don't have a mini hdmi cable for the Pi 4, but using ssh and VNC fine
